supabase_url = "https://jncgqebhmcdojjowthmp.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuY2dxZWJobWNkb2pqb3d0aG1wIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzgzNjc0NSwiZXhwIjoyMDYzNDEyNzQ1fQ.WEd3LXOMP3uHWLAYrJXMS_n5fvAYu0-5bs1E73hbQnE"


